chore: calculate only missing contour levels
cheminfo/nmrium pull request #3224
Opened 2024-09-02 14:44 UTC by jobo322

2024-09-04 09:31 UTC, targos requested changes
I will try to point the problems when I have more time but I suggest you spend time learning React on your side because the things you did with the hooks are very wrong.

2024-09-04 09:52 UTC, jobo322 commented
> I will try to point the problems when I have more time but I suggest you spend time learning React on your side because the things you did with the hooks are very wrong.

it were very expected, because I have not idea of react, but I would like show to luc, the behavior of contour plot cache while we wait for hamed, The time of contours generation reduce a lot when all the levels are cached.

2024-09-06 06:31 UTC, targos commented
I'm not planning to refactor it, but I would like to review it when it's ready

2024-09-06 09:52 UTC, hamed-musallam commented
@jobo322 

I created a specialized context to handle contour calculations per nucleus https://github.com/cheminfo/nmrium/blob/f2d29f990ebda05dab0b950d1c96222db9827922/src/component/2d/ft/ContoursContext.tsx#L38-L53

This requires additional work: 
 1. Move the contour options from the `display` object within the spectrum object to `view` to avoid recalculating the contours when those options change. 
 2. Calculate all the contour levels once. Please review the `drawContours` function and make the necessary changes.

https://github.com/cheminfo/nmrium/blob/f2d29f990ebda05dab0b950d1c96222db9827922/src/component/2d/ft/ContoursContext.tsx#L23-L30


We have a custom hook, useContours, which returns an object where each key is a spectrum ID, and the value is an object with the following structure:``` { positive: { contours: [], timeout: boolean }, negative: { contours: [], timeout: boolean } }```.

2024-09-06 15:02 UTC, jobo322 commented
It is not feasible for big files to calculate all the levels at once. 
is it possible to pass the `boundaries` to useContours?

2024-09-12 08:48 UTC, lpatiny commented
> It is not feasible for big files to calculate all the levels at once. is it possible to pass the `boundaries` to useContours?

@jobo322 Yes this is what I was afraid of. What is the maximal number of points in both directions that seems reasonable to you ?

This would make things much more complex because we can not simply cache the results as we were thinking before.

If we can cache currently the full analysis we should merge this PR once Michael has validated it. We will then think in another issue how to reduce the resolution and have 'quadrants' or something like that when data is too big. I may help on this and add some methods in ml-spectra-processing.

2024-09-13 07:19 UTC, lpatiny commented
@hamed-musallam Are you working on this PR ? Currently it does not work at all seems to me and is very slow.
If it is easier we can close this PR and start over again because I would expect that it should not be such a difficult feature to implement to create an object cache that contains `{key: level, value: contour}`.

2024-09-13 07:26 UTC, hamed-musallam commented
> @hamed-musallam Are you working on this PR ? Currently it does not work at all seems to me and is very slow. If it is easier we can close this PR and start over again because I would expect that it should not be such a difficult feature to implement to create an object cache that contains `{key: level, value: contour}`.

No, but I believe Alejandro is working on this PR. It's better to keep it open to preserve the comments, and we can reset the branch to the main

2024-09-13 12:16 UTC, lpatiny commented
You may also chedk:
- https://github.com/cheminfo/nmrium/pull/3243

2024-11-22 05:10 UTC, lpatiny commented
@jobo322 Could you try to rebase this branch ?

2025-01-10 08:45 UTC, lpatiny commented
Will be done in:
- https://github.com/cheminfo/nmrium/pull/3243

2025-01-10 08:45 UTC, closed without merging